spring:
  application:
    name: ingestor
    environment: local
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    compression-type: lz4 # use lz4 for better compression and lower memory footprint for messages
  redis:
    host: localhost
    port: 6379
    password: ""
    timeout: 6000
    lettuce:
      pool:
        # hard limit of connections
        max-active: 30 # currently needs 21 (2 consumer + 1 job) but add more for buffer
        # max idle connections (unused but ready)
        ## excess idle connections get closed to save resources
        max-idle: 15
        # pool proactively creates connections to meet this minimum if not met
        min-idle: 5 # maintain some baseline for a quick response

server:
  port: 8080

kafka:
  binance:
    topic: binance-topic
    latest:
      topic: binance-latest-topic
      group: binance-latest-group
      consumers: 10
    dlt:
      topic: binance-dlt-topic
      group: binance-dlt-consumer-group
      enabled: false
      consumers: 2
  coinbase:
    topic: coinbase-topic
    latest:
      topic: coinbase-latest-topic
      group: coinbase-latest-group
      consumers: 10
    dlt:
      topic: coinbase-dlt-topic
      group: coinbase-dlt-consumer-group
      enabled: false
      consumers: 2
  monitoring:
    topic: monitor-topic
  streams:
    binance:
      applicationId: binance-stream
      commitInterval: 500
      gracePeriod: 1000
#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka.clients.consumer: DEBUG