spring:
  application:
    name: ingestor
    environment: local
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093
    compression-type: lz4 # use lz4 for better compression and lower memory footprint for messages
  redis:
    host: localhost
    port: 6379
    password: ""
    timeout: 6000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2

server:
  port: 8080

kafka:
  binance:
    topic: binance-topic
    latest:
      topic: binance-latest-topic
      group: binance-latest-group
      consumers: 10
    dlt:
      topic: binance-dlt-topic
      group: binance-dlt-consumer-group
      enabled: false
      consumers: 2
  coinbase:
    topic: coinbase-topic
    latest:
      topic: coinbase-latest-topic
      group: coinbase-latest-group
      consumers: 10
    dlt:
      topic: coinbase-dlt-topic
      group: coinbase-dlt-consumer-group
      enabled: false
      consumers: 2
  monitoring:
    topic: monitor-topic
    dlt:
      topic: monitor-dlt-topic
  streams:
    binance:
      applicationId: binance-stream
      commitInterval: 500
      gracePeriod: 1000

#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka.clients.consumer: DEBUG